# Generated by Django 5.0.6 on 2024-06-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Espace_CT', '0004_project_finished_alter_project_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='finished',
        ),
    ]
