# Generated by Django 5.1 on 2024-09-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espace_CT', '0008_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=300)),
                ('password', models.CharField(default='root', max_length=200)),
            ],
        ),
    ]
