# Generated by Django 5.1 on 2024-09-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espace_CT', '0009_minecraftserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minecraftserver',
            name='password',
            field=models.CharField(default='pwd', max_length=200),
        ),
    ]
