# Generated by Django 5.1 on 2024-09-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Espace_CT', '0010_alter_minecraftserver_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minecraftserver',
            old_name='title',
            new_name='name',
        ),
    ]
