# Generated by Django 5.1 on 2024-09-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espace_CT', '0011_rename_title_minecraftserver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserver',
            name='rcon_port',
            field=models.CharField(default='25575', max_length=5),
        ),
    ]
