# Generated by Django 5.0.6 on 2024-06-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espace_CT', '0002_project_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cover',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ImageField(default='missing-file.jpg', upload_to='images/'),
        ),
    ]
