# Generated by Django 5.0.6 on 2024-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espace_CT', '0003_remove_project_cover_project_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(default='images/missing-file.jpg', upload_to='images/'),
        ),
    ]
