# Generated by Django 5.0.6 on 2024-06-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espace_CT', '0005_remove_project_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
